name = "yow"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "yow"
licences = ["Apache-2.0"]
repository = { type = "github", user = "emptist", repo = "yow" }
links = [{ title = "Website", href = "caishen.streamlit.app" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
glacier = ">= 1.3.2 and < 2.0.0"
